# Sample configuration for RateMyKB

# AI Engine configuration
ai_engine:
  # URL of the AI API endpoint
  url: "http://localhost:11434/"
  # Model to use for classification
  model: "gemma3:12b"
  #model: "llama3.2:latest"
  #model: "gemma3:1b"

# Scan settings
scan_settings:
  # File extension to scan for
  file_extension: ".md"
  # Directories to exclude from scanning
  exclude_directories:
    - ".obsidian"
    - ".git"
    - ".github"
    - "node_modules"

# Prompt configuration
prompt_config:
  # Prompt to use for classifying content quality
  quality_classification_prompt: >
    **Task:** Classify the provided markdown note content based on its substance.

    **Instructions:**
    1.  Review the main content of the note below. Ignore any frontmatter (like YAML blocks at the start).
    2.  Choose **one** category that best describes the content's quality and substance:
        * **'Empty'**: The content section is effectively blank, contains only template text/scaffolding, or is missing after ignoring frontmatter.
        * **'Low quality'**: The content is present but extremely minimal, lacks detail or a clear point, or seems incomplete/placeholder.
        * **'Good enough'**: The content provides a clear point, concept, or piece of information, even if brief. It has substance and is more than just a placeholder.
    3.  Respond **only** with a JSON object containing the classification

    **Example Output Format:**
    {
      "classification": "Empty"
    }

# Exclusion file configuration
exclusion_file:
  # Path to the file containing Obsidian links to exclude from scanning
  # This should be relative to the target directory or an absolute path
  path: "quality_exclude_links.md" 